version: 0.1
os: linux

files:
  - source: /
    destination: /home/ubuntu/gitaction-react
    overwrite: yes
permissions:
  - object: /home/ubuntu/gitaction-react
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
